version: "2.0"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=umdio
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redoc:
    image: redocly/redoc
    environment:
      - SPEC_URL=http://localhost:3000/v1/spec.yaml
    ports:
      - 8080:80
  umdio:
    build: .
    links:
      - postgres
    volumes:
      - ./:/umdio
    ports:
      - 3000:3000
      - 1234:1234
      - 26162:26162
    # command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 -- rake up
    command: bundle exec rake up
    restart: always
