# Site settings
title: umd.io | Documentation
email: hi@umd.io
description: > # this means to ignore newlines until "baseurl:"
  An API for the University of Maryland's data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://umd.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  umdio

# Build settings
markdown: kramdown
destination: ../public
sass:
  sass_dir: _sass
  style: :compressed

