name: build-docs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.1
    - name: Install redoc-cli
      run: sudo npm install -g redoc-cli
    - name: Build
      run: redoc-cli bundle ./openapi.yaml
    - name: Move
      run: mv redoc-static docs/index.html
    - name: Commit
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "${GITHUB_ACTOR}@bots.github.com"
        git add docs/index.html
        git commit -m "[Build] Build docs"
        git push
